/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.InvoiceItem;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceItemRecord extends UpdatableRecordImpl<InvoiceItemRecord> implements Record5<Integer, Long, Integer, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.invoice_item.id</code>.
     */
    public InvoiceItemRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.invoice_item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.invoice_item.price</code>.
     */
    public InvoiceItemRecord setPrice(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.invoice_item.price</code>.
     */
    public Long getPrice() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.invoice_item.amount</code>.
     */
    public InvoiceItemRecord setAmount(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.invoice_item.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.invoice_item.nomenclature</code>.
     */
    public InvoiceItemRecord setNomenclature(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.invoice_item.nomenclature</code>.
     */
    public Long getNomenclature() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.invoice_item.invoice_id</code>.
     */
    public InvoiceItemRecord setInvoiceId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.invoice_item.invoice_id</code>.
     */
    public Long getInvoiceId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Long, Integer, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Long, Integer, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return InvoiceItem.INVOICE_ITEM.ID;
    }

    @Override
    public Field<Long> field2() {
        return InvoiceItem.INVOICE_ITEM.PRICE;
    }

    @Override
    public Field<Integer> field3() {
        return InvoiceItem.INVOICE_ITEM.AMOUNT;
    }

    @Override
    public Field<Long> field4() {
        return InvoiceItem.INVOICE_ITEM.NOMENCLATURE;
    }

    @Override
    public Field<Long> field5() {
        return InvoiceItem.INVOICE_ITEM.INVOICE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPrice();
    }

    @Override
    public Integer component3() {
        return getAmount();
    }

    @Override
    public Long component4() {
        return getNomenclature();
    }

    @Override
    public Long component5() {
        return getInvoiceId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPrice();
    }

    @Override
    public Integer value3() {
        return getAmount();
    }

    @Override
    public Long value4() {
        return getNomenclature();
    }

    @Override
    public Long value5() {
        return getInvoiceId();
    }

    @Override
    public InvoiceItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public InvoiceItemRecord value2(Long value) {
        setPrice(value);
        return this;
    }

    @Override
    public InvoiceItemRecord value3(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public InvoiceItemRecord value4(Long value) {
        setNomenclature(value);
        return this;
    }

    @Override
    public InvoiceItemRecord value5(Long value) {
        setInvoiceId(value);
        return this;
    }

    @Override
    public InvoiceItemRecord values(Integer value1, Long value2, Integer value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceItemRecord
     */
    public InvoiceItemRecord() {
        super(InvoiceItem.INVOICE_ITEM);
    }

    /**
     * Create a detached, initialised InvoiceItemRecord
     */
    public InvoiceItemRecord(Integer id, Long price, Integer amount, Long nomenclature, Long invoiceId) {
        super(InvoiceItem.INVOICE_ITEM);

        setId(id);
        setPrice(price);
        setAmount(amount);
        setNomenclature(nomenclature);
        setInvoiceId(invoiceId);
    }
}
