/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Nomenclature;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NomenclatureRecord extends UpdatableRecordImpl<NomenclatureRecord> implements Record3<Integer, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.nomenclature.id</code>.
     */
    public NomenclatureRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.nomenclature.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.nomenclature.internal_code</code>.
     */
    public NomenclatureRecord setInternalCode(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.nomenclature.internal_code</code>.
     */
    public Long getInternalCode() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.nomenclature.name</code>.
     */
    public NomenclatureRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.nomenclature.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Nomenclature.NOMENCLATURE.ID;
    }

    @Override
    public Field<Long> field2() {
        return Nomenclature.NOMENCLATURE.INTERNAL_CODE;
    }

    @Override
    public Field<String> field3() {
        return Nomenclature.NOMENCLATURE.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getInternalCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getInternalCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public NomenclatureRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NomenclatureRecord value2(Long value) {
        setInternalCode(value);
        return this;
    }

    @Override
    public NomenclatureRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public NomenclatureRecord values(Integer value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NomenclatureRecord
     */
    public NomenclatureRecord() {
        super(Nomenclature.NOMENCLATURE);
    }

    /**
     * Create a detached, initialised NomenclatureRecord
     */
    public NomenclatureRecord(Integer id, Long internalCode, String name) {
        super(Nomenclature.NOMENCLATURE);

        setId(id);
        setInternalCode(internalCode);
        setName(name);
    }
}
