/*
 * This file is generated by jOOQ.
 */
package db.tables;


import db.Keys;
import db.Public;
import db.tables.records.InvoiceItemRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceItem extends TableImpl<InvoiceItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.invoice_item</code>
     */
    public static final InvoiceItem INVOICE_ITEM = new InvoiceItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvoiceItemRecord> getRecordType() {
        return InvoiceItemRecord.class;
    }

    /**
     * The column <code>public.invoice_item.id</code>.
     */
    public final TableField<InvoiceItemRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.invoice_item.price</code>.
     */
    public final TableField<InvoiceItemRecord, Long> PRICE = createField(DSL.name("price"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.invoice_item.amount</code>.
     */
    public final TableField<InvoiceItemRecord, Integer> AMOUNT = createField(DSL.name("amount"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.invoice_item.nomenclature</code>.
     */
    public final TableField<InvoiceItemRecord, Long> NOMENCLATURE = createField(DSL.name("nomenclature"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.invoice_item.invoice_id</code>.
     */
    public final TableField<InvoiceItemRecord, Long> INVOICE_ID = createField(DSL.name("invoice_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private InvoiceItem(Name alias, Table<InvoiceItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private InvoiceItem(Name alias, Table<InvoiceItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.invoice_item</code> table reference
     */
    public InvoiceItem(String alias) {
        this(DSL.name(alias), INVOICE_ITEM);
    }

    /**
     * Create an aliased <code>public.invoice_item</code> table reference
     */
    public InvoiceItem(Name alias) {
        this(alias, INVOICE_ITEM);
    }

    /**
     * Create a <code>public.invoice_item</code> table reference
     */
    public InvoiceItem() {
        this(DSL.name("invoice_item"), null);
    }

    public <O extends Record> InvoiceItem(Table<O> child, ForeignKey<O, InvoiceItemRecord> key) {
        super(child, key, INVOICE_ITEM);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<InvoiceItemRecord, Integer> getIdentity() {
        return (Identity<InvoiceItemRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<InvoiceItemRecord> getPrimaryKey() {
        return Keys.INVOICE_ITEM_PKEY;
    }

    @Override
    public List<UniqueKey<InvoiceItemRecord>> getKeys() {
        return Arrays.<UniqueKey<InvoiceItemRecord>>asList(Keys.INVOICE_ITEM_PKEY);
    }

    @Override
    public List<ForeignKey<InvoiceItemRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InvoiceItemRecord, ?>>asList(Keys.INVOICE_ITEM__INVOICE_ITEM_NOMENCLATURE_FKEY, Keys.INVOICE_ITEM__INVOICE_ITEM_INVOICE_ID_FKEY);
    }

    public Nomenclature nomenclature() {
        return new Nomenclature(this, Keys.INVOICE_ITEM__INVOICE_ITEM_NOMENCLATURE_FKEY);
    }

    public Invoice invoice() {
        return new Invoice(this, Keys.INVOICE_ITEM__INVOICE_ITEM_INVOICE_ID_FKEY);
    }

    @Override
    public List<Check<InvoiceItemRecord>> getChecks() {
        return Arrays.<Check<InvoiceItemRecord>>asList(
              Internal.createCheck(this, DSL.name("invoice_item_amount_check"), "((amount >= 0))", true)
            , Internal.createCheck(this, DSL.name("invoice_item_price_check"), "((price > 0))", true)
        );
    }

    @Override
    public InvoiceItem as(String alias) {
        return new InvoiceItem(DSL.name(alias), this);
    }

    @Override
    public InvoiceItem as(Name alias) {
        return new InvoiceItem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InvoiceItem rename(String name) {
        return new InvoiceItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InvoiceItem rename(Name name) {
        return new InvoiceItem(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Long, Integer, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
