/*
 * This file is generated by jOOQ.
 */
package db;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.invoice_id_seq</code>
     */
    public static final Sequence<Integer> INVOICE_ID_SEQ = Internal.createSequence("invoice_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.invoice_item_id_seq</code>
     */
    public static final Sequence<Integer> INVOICE_ITEM_ID_SEQ = Internal.createSequence("invoice_item_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.nomenclature_id_seq</code>
     */
    public static final Sequence<Integer> NOMENCLATURE_ID_SEQ = Internal.createSequence("nomenclature_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.organisation_id_seq</code>
     */
    public static final Sequence<Integer> ORGANISATION_ID_SEQ = Internal.createSequence("organisation_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
